"use client";
import { Download } from "lucide-react";
import { Button } from "../ui/button";

interface DownloadSummaryButtonProps {
  title: string;
  summary_text: string;
  file_name: string;
  created_at: string;
}
export default function DownloadSummaryButton({
  title,
  summary_text,
  file_name,
  created_at,
}: DownloadSummaryButtonProps) {
    
  const handleDownload = () => {
    const summaryContent = `# ${title}
Generated Summary
Generated on: ${new Date(created_at).toLocaleString()}

${summary_text}

Original file: ${file_name}
Generated by Sommaire`;
    const blob = new Blob([summaryContent], { type: "text/plain" });
    const url = URL.createObjectURL(blob);
    const a = document.createElement("a");
    a.href = url;
    a.download = `Summary-${title.replace(/[^a-z0-9]/gi, "-")}.txt`;
    a.click();
    URL.revokeObjectURL(url);
  };

  return (
    <Button
      size="sm"
      className="h-8 px-3 bg-rose-100 text-rose-600 hover:text-rose-700 hover:bg-rose-50"
      onClick={handleDownload}
    >
      <Download className="size-4 me-1" />
      تحميل الملخص
    </Button>
  );
}
